### ISSUE TITLE
server returns error 500

### ISSUE THREAD

**Issue by blouisdiddy** [serenita-org/ethstaker.tax#43]
something changed since this was clearly working before. Entering 1 or N validators by either index of account will result in this return code.

**Comment by eth2353** [comment]
Thanks for reporting this. We're aware of the issue and are working on resolving this. We have switched the ethstaker.tax website to use a fallback node for now while we work on fixing the main node that is used behind the scenes.

The website should be usable again but may experience brief periods of instability over the coming days.

I'll close this issue once everything's back to normal.

**Comment by eth2353** [comment]
The website should be much more stable at this point, closing the issue
