### ISSUE TITLE
Failed to get rewards - Unexpected fee recipient None for 8530137 (expected: 

### ISSUE THREAD

**Issue by pacts-bravos** [serenita-org/ethstaker.tax#61]
When adding fee recipient addresses it gives this error (with my fee recipient addresses removed):
Failed to get rewards - Unexpected fee recipient None for 8530137 (expected: ['0x<omitted>', '0x<omitted>'])

**Comment by eth2353** [comment]
Thanks for reporting, I just looked into this. I found a small bug which explains why it says None for fee recipient in the error message. This bug has been fixed.

Apart from that however, you didn't use commas to separate your fee recipient addresses which is what actually caused the error message in the first place. Please use commas to separate your fee recipient addresses, that should take care of the issue. Let me know if it works for you!
