### ISSUE TITLE
Hi again

### ISSUE THREAD

**Issue by Tachyonica** [serenita-org/ethstaker.tax#69]
Sadly the tool no longer works again - pressing the "ADD" button after selecting "deposit address" and inserting a valid deposit address has no effect. Any ideas?

**Comment by eth2353** [comment]
Hey, there was a temporary issue with certificates resulting in ethstaker.tax being unable to retrieve the validators based on the deposit address (this is one of the very few external dependencies, we use beaconcha.in to map deposit addresses to validator indexes).

Should be fixed now 🙂

**Comment by Tachyonica** [comment]
Thanks! ♥️
