### ISSUE TITLE
Incorrect reporting of Smooth Pool Receipient

### ISSUE THREAD

**Issue by bwargon** [serenita-org/ethstaker.tax#70]
Getting this error message which i don't understand "Failed to get rewards - Request failed with status code 500 Block reward for slot 8674315 proposed by RP minipool (0xdddf2dff420b4b2f28f300e6b777e94e5cecd8e7 / 852604) did not go to smoothing pool (0xd4e96ef8eee8678dbff4d535e033ed1a4f7605b7) or fee distributor (0x711a2cd0d55dc30c6636726f30bfc33ff0e3b53d) but 0x1f9090aae28b8a3dceadf281b0f12828e676c326!"

If you look at https://beaconcha.in/slot/dc10243b1b2fb974b8466263ac3ae954a65ad6ec7a23a184dc3b282a5c6806de it says the MEV reciepient was the smoothing pool (

"MEV Reward Recipient:
[0xd4E96eF8eee8678dBFf4d535E033Ed1a4F7605b7](https://beaconcha.in/address/0xd4e96ef8eee8678dbff4d535e033ed1a4f7605b7)"

??

**Comment by eth2353** [comment]
Looked into this, in this case the block reward processing failed so the error message should have been a little different. I fixed the incorrect error message and also this block's rewards in the database so everything should be working fine again!

**Comment by bwargon** [comment]
Thank you
