### ISSUE TITLE
Unexpected fee recipient error

### ISSUE THREAD

**Issue by xlog4n** [serenita-org/ethstaker.tax#77]
"Failed to get rewards - Unexpected fee recipient 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx for slot 8404228 (expected: one of ['0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'])" 

Redacted addresses. Let me know if you need the addresses. 

Trying to look at my earnings for YTD (2024) and receiving this error - not a problem for 2023 or 2022. Report runs fine without anything in fee recipient field (2024), but I get the error above when I put something in the fee recipient field.

**Comment by eth2353** [comment]
Hey there, this is again an issue with indexing of MEV, I fixed it just now for this builder 👍
