### ISSUE TITLE
Failed to get rewards - Unable to find RP minipools for all validators

### ISSUE THREAD

**Issue by darkwinter56** [serenita-org/ethstaker.tax#80]
I cannot calculate rewards on several rocketpool deposit/node addresses. E.g. validator index 1007727 works, but the other ones on deposit address 0xD7751a57b1149C2B24302f3A3Cb27568982e2481 do not.

**Comment by eth2353** [comment]
Should be fixed now with #81 , looks like I missed the new minipool manager address!
