### ISSUE TITLE
Failed to get rewards

### ISSUE THREAD

**Issue by pacts-bravos** [serenita-org/ethstaker.tax#82]
Hello,

I am unable to get the calculations. Fails with the error
`Failed to get rewards - Request failed with status code 500 Execution layer rewards not available - missing data for proposer XXXXXX, slot YYYYYYY`

Thank you!

**Comment by pacts-bravos** [comment]
Hi, tried it few times today. Including just now.

**Comment by eth2353** [comment]
Perfect, I just fixed that slot's data for you, please check if everything works

**Comment by pacts-bravos** [comment]
Thank you! Worked now!

**Comment by eth2353** [comment]
Hey @MrYukonC1 fixed that slot for you!
