### ISSUE TITLE
Unexpected fee recipient

### ISSUE THREAD

**Issue by reth3** [serenita-org/ethstaker.tax#85]
Hello,

Please help with the following error:
> Failed to get rewards - Unexpected fee recipient A for slot X (expected: one of ['B'])

Note, beaconcha.in shows the correct address as the MEV recipient for this slot.

Thank you.

**Comment by eth2353** [comment]
Hey there!

I'm not 100% sure if I managed to fix your slot but I did reindex data for about 9000 incorrectly indexed slots today. Can you check if your input data still shows errors?

If you still see errors, please send me the approximate timestamp at which you tried it so I can find your request in the logs.

**Comment by reth3** [comment]
I'm still seeing the error. Approximate time Thu Nov 14 17:29:39 UTC 2024.

Thank you!

**Comment by eth2353** [comment]
Perfect, that slot is fixed now too 👍

**Comment by eth2353** [comment]
(FYI, the ethstaker.tax API will be down for about an hour or two, but once it's back up you should be able to retrieve the data)

**Comment by reth3** [comment]
It's working now, thank you!
